from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

model = ChatOpenAI(model = 'gpt-4', temperature= 0.5) # temp means the randomness and creativity in the reponse generated by the model, it ranges form 0 to 2.
result = model.invoke("What is the capital of india?")

print(result) # provides the result with content and it's metadata.

print(result.content) # Only content is provided such as "the capital of India is New Delhi"